# Generated by Django 2.2.5 on 2021-12-24 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=20, verbose_name='Mật khẩu')),
                ('name', models.CharField(max_length=50, verbose_name='Tên người dùng')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Quản trị viên'), (2, 'Người dùng')], verbose_name='Phân quyền')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lat', models.CharField(max_length=100, verbose_name='Lat')),
                ('lng', models.CharField(max_length=100, verbose_name='Lng')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian khởi tạo')),
                ('user', models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, to='app_tracking_location.User', verbose_name='Người dùng')),
            ],
        ),
    ]
