# Generated by Django 2.2.5 on 2021-12-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracking_location', '0002_auto_20211229_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date'], 'verbose_name': 'Lịch sử', 'verbose_name_plural': 'Danh sách lịch sử di chuyển'},
        ),
        migrations.AddField(
            model_name='user',
            name='diachi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ'),
        ),
    ]
