# Generated by Django 2.2.5 on 2021-12-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracking_location', '0003_auto_20211229_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cmnd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chứng minh nhân dân'),
        ),
    ]
